FROM rust:1.74 as build

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install --no-install-recommends --assume-yes \
      protobuf-compiler

RUN cargo install cargo-watch

WORKDIR /logs
ENTRYPOINT cargo-watch -x run
