FROM busybox:1.35.0-uclibc as busybox

FROM surrealdb/surrealdb:1.0.0
COPY --from=busybox /bin/sh /bin/sh
COPY --from=busybox /bin/mkdir /bin/mkdir
COPY --from=busybox /bin/cat /bin/cat
COPY --from=busybox /bin/chmod /bin/chmod

RUN echo "alias sur='/surreal'" >> ~/.bash_aliases

ENTRYPOINT /surreal start memory --log info -A